[package]
name = "offline_crates_server"
version = "0.1.0"
authors = ["Martyn P <>"]
edition = "2018"


[dependencies]
rocket = "0.4.2"
clap = "2.33.0"
serde_json = "1.0.44"
repository = { path = "../repository" }
