[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
env_logger = "0.11.6"
rocket = "0.5.1"
serde = { version = "1.0.217", features = ["derive"] }
glob = "0.3.2"
log = "0.4.25"

lib = { path = "../lib" }
